### ISSUE TITLE
Ability to disable groups and items in groups

### ISSUE THREAD

**Issue by koljada** [shentao/vue-multiselect#1119]
### Reproduction Link
https://jsfiddle.net/koljada/dq471nv8/20/
### Steps to reproduce
1. Create a multiselect with groups
2. Try to disable a group
3. Try to disable an item in some group
### Expected behavior
The whole group should be disabled in step 2.
Single item in group should be disabled in step 3.
### Actual behavior
`$isDisabled` property is ignored in step 2, the whole group is enabled and selectable.
Adding `$isDisabled` property to the group's item object causes an error.

**Comment by worldofprasanna** [comment]
@koljada I think the problem is related to the version you are using which is 2.1.0.

This issue is fixed in release 2.1.4 - https://github.com/shentao/vue-multiselect/releases/tag/2.1.4

**Comment by koljada** [comment]
Thank you, @worldofprasanna!
I updated to 2.1.6 and now it's possible to disable an individual item but it still not possible to disable the whole group.

Also I think it would be nice to update script's version in cdn links: [here](https://vue-multiselect.js.org/)

**Comment by worldofprasanna** [comment]
@koljada It seems if you disable all the individual options in the group, then the group would be disabled. 

I am working on a PR to disable entire group, till then you can have this as the workaround

**Comment by koljada** [comment]
@worldofprasanna Thank you
