### ISSUE TITLE
Placeholder wraps down with multiple: true, searchable: false

### ISSUE THREAD

**Issue by tochoromero** [shentao/vue-multiselect#677]
If you create a multiselect with `multiple = true` and `searchable = false` the placeholder element wraps down even though there is plenty of space for it to remain on the same line.

<img width="533" alt="screen shot 2018-03-15 at 8 19 17 am" src="https://user-images.githubusercontent.com/4211135/37472555-9b1f4a88-2829-11e8-9a24-d70a505e2fb1.png">

https://codepen.io/tochoromero/pen/OvXPbw

**Comment by shentao** [comment]
Hey! Would you be able to check this on the new master? I think it is already fixed and should be released soon.

**Comment by tochoromero** [comment]
I still see it on master. On my actual project I installed it directly from github:master

**Comment by shentao** [comment]
You might be using the old dist files (which I haven’t been updating so far, since the release is not ready. I will bundle and upload the fresh dist files to GH.
